# Generated by Django 2.2.12 on 2020-05-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryimage',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
