# Generated by Django 2.2.12 on 2020-05-17 21:14

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_queryimage_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetImage',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('url', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(max_length=32)),
                ('metadata', djongo.models.fields.DictField(null=True)),
            ],
        ),
    ]
