# Generated by Django 2.2.12 on 2020-05-20 10:59

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_datasetimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryImageSimilarity',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('query_image_id', models.CharField(max_length=128)),
                ('similarities', djongo.models.fields.ListField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
